 version: '3.8'

services:
  # Mini PM2 应用
  mini-pm2:
    build: .
    ports:
      - "8100:8100"
    environment:
      - STORAGE_TYPE=redis
      - REDIS_URL=redis://redis:6379
      - REDIS_DB=0
      - LOG_LIMIT=500
      - CHECK_INTERVAL=30
      - DEBUG=false
    volumes:
      - ./logs:/app/logs
      - ./exports:/app/exports
      - ./tasks.json:/app/tasks.json
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - mini-pm2-network

  # Redis 服务
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - mini-pm2-network

  # Nginx 反向代理 (可选)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - mini-pm2
    restart: unless-stopped
    networks:
      - mini-pm2-network
    profiles:
      - production

volumes:
  redis-data:

networks:
  mini-pm2-network:
    driver: bridge